---
title: "Homework 4"
author: "Xinyi Lin"
date: "10/5/2019"
output: word_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(survey)
```

```{r}
military = read.csv("./military.csv") %>% 
  mutate(XCPAY1R = ifelse(XCPAY1R==3, 2, XCPAY1R),
         paygrade = ifelse(XCPAY1R %in% c(4,5,6,7), 3, XCPAY1R),
         GENDER = XSEXR,
         RACETH = XRETH4R) %>% 
  select(-XCPAY1R, -XSEXR, -XRETH4R)
population = read.csv("./population.csv") %>% 
  mutate(GENDER = as.factor(GENDER),
         RACETH = as.factor(RACETH),
         paygrade = as.factor(paygrade))
```

## Question a

**Poststratification**

```{r, warning=FALSE}
# question a
dclus1 = svydesign(ids = ~X, strata = ~STRATUM, fpc = ~NSTRAT, weights = ~weight, data = military)
dclus1p = postStratify(dclus1, ~ RACETH + GENDER + paygrade, population)
military$ps_wei = weights(dclus1p)
summary(military$ps_wei)
hist(military$ps_wei)
```


**Raking**

```{r}
pop.race = population %>% 
  group_by(RACETH) %>% 
  summarize(Freq=sum(count_s)) %>% 
  ungroup() 
pop.gender = population %>% 
  group_by(GENDER) %>% 
  summarize(Freq=sum(count_s)) %>% 
  ungroup() 
pop.pay = population %>% 
  group_by(paygrade) %>% 
  summarize(Freq=sum(count_s)) %>% 
  ungroup() 
rclus1 = rake(dclus1, list(~RACETH, ~GENDER, ~paygrade), list(pop.race, pop.gender, pop.pay))
military$rak_wei = weights(rclus1)
summary(military$rak_wei)
hist(military$rak_wei)
```

## Question b

```{r, warning=FALSE}
# question b
# population data
pop_weight = population %>% 
  group_by(paygrade) %>% 
  summarize(pop_wei=sum(count_s)) %>% 
  ungroup() 
military %>% 
  group_by(paygrade) %>% 
  summarize(adj_wei = sum(weight),
            ps_wei = sum(ps_wei),
            rak_wei = sum(rak_wei)) %>% 
  ungroup() %>% 
  mutate(pop_wei = pop_weight$pop_wei) %>% 
  knitr::kable()
```

According to results, we can find that even though adjusted weights of each psu given by post-stratification and raking are not the same, weights total of each payroll groups are the same and both of them are the same as population total weights in each payroll groups. 

**Appendix**

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```
